# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:10.13
  working_directory: ~/mdb-feathers

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
            - npm-dependencies
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: npm-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Run tests
          command: yarn test

  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: docker build . -f docker/Dockerfile -t wlucjan/mdb-feathers:$CIRCLE_SHA1
  deploy:
    <<: *defaults
    steps:
      - run:
          name: Deploy Docker Image
          command: |
            docker login -u $HEROKU_LOGIN -p $HEROKU_API_KEY registry.heroku.com
            docker tag wlucjan/mdb-feathers:$CIRCLE_SHA1 registry.heroku.com/$HEROKU_APP_NAME/web
            docker push registry.heroku.com/$HEROKU_APP_NAME/web
workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
